version: '3.1'
services:
  db:
    build: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@technoware
      MYSQL_DATABASE: technoware
      MYSQL_USER: technoware-banco
      MYSQL_PASSWORD: db@technoware
    ports:
      - 3306:3306
    volumes:
      - technoware_db_data:/var/lib/mysql
  springboot:
    build: .
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/technoware?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=technoware-banco
      - SPRING_DATASOURCE_PASSWORD=db@technoware
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  technoware_db_data: